### ISSUE TITLE
material-design-icons on NavBar are not displayed

### ISSUE THREAD

**Issue by nguyenduy** [corupta/pdf-viewer-reactjs-bulma-wrapped#1]
I am using this component in my TypeScript project and import it like this:
// @ts-ignore
import PDFViewer from "pdf-viewer-reactjs-bulma-wrapped";

Somehow, the icons on NavBar are not displayed. Could you check this issue?

![Icons on Nav Bar are not displayed](https://user-images.githubusercontent.com/1797796/93113734-950e9480-f687-11ea-8537-fbcf0a09c3f2.png)

**Comment by nguyenduy** [comment]
Never mind! I forgot to set up material-design-icons.

**Comment by italofsan** [comment]
Hello, how do I set up material-design-icons in my project?

**Comment by corupta** [comment]
Hi, doing `npm i material-design-icons` or `yarn add material-design-icons` should suffice.
